PracticaNetSignalR/Controllers/ChartsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PracticaNetSignalR.Models;

namespace PracticaNetSignalR.Controllers
{
    public class ChartsController : Controller
    {

        private readonly ApplicationDBContext _context;


        public ChartsController(ApplicationDBContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            List<object> data = new List<object>();        
            var lista = _context.Programming.ToList();
            foreach (var item in lista)
            {
                object[] obj = new object[2];
                obj[0] = item.Name;
                obj[1] = 0;
                data.Add(obj);
            }
            ViewBag.data = data;
            return View(lista);
        }

        public async Task<IActionResult> Room(int id)
        {
            var room = _context.Room.FindAsync(id).Result;
            return View(room);
        }
    }
}

PracticaNetSignalR/Controllers/ChatsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using PracticaNetSignalR.Hubs;
using PracticaNetSignalR.Models;

namespace PracticaNetSignalR.Controllers
{
    public class ChatsController : Controller
    {

        private readonly ApplicationDBContext _context;


        public ChatsController(ApplicationDBContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            return View();
        }

        public async Task<IActionResult> List()
        {
            return _context.Room != null ?
                        View(await _context.Room.ToListAsync()) :
                        Problem("Entity set 'ApplicationDBContext.Room'  is null.");
        }

        public async Task<IActionResult> Room(int id)
        {
            var room = _context.Room.FindAsync(id).Result; 
            return View(room);
        }
    }
}

PracticaNetSignalR/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using PracticaNetSignalR.Hubs;
using PracticaNetSignalR.Models;

namespace PracticaNetSignalR.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly ApplicationDBContext _context;
        private readonly IHubContext<ProjectHub> _projectHub;

        public ProjectsController(ApplicationDBContext context, IHubContext<ProjectHub> projectHub)
        {
            _context = context;
            _projectHub = projectHub;
        }


        public async Task<IActionResult> Index()
        {
            return _context.Project != null ?
                        View(await _context.Project.ToListAsync()) :
                        Problem("Entity set 'ApplicationDBContext.Project'  is null.");
        }

        [HttpGet]
        public IActionResult GetProjects()
        {
            var res = _context.Project.ToList();
            return Ok(res);
        }

       
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Project == null)
            {
                return NotFound();
            }

            var Project = await _context.Project
                .FirstOrDefaultAsync(m => m.Id == id);
            if (Project == null)
            {
                return NotFound();
            }

            return View(Project);
        }

       
        public IActionResult Create()
        {
            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,Url,Repository")] Project Project)
        {
            if (ModelState.IsValid)
            {
                _context.Add(Project);
                await _context.SaveChangesAsync();
                await _projectHub.Clients.All.SendAsync("LoadProyects");
                return RedirectToAction(nameof(Index));
            }
            return View(Project);
        }

      
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Project == null)
            {
                return NotFound();
            }

            var Project = await _context.Project.FindAsync(id);
            if (Project == null)
            {
                return NotFound();
            }
            return View(Project);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,Url,Repository")] Project Project)
        {
            if (id != Project.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(Project);
                    await _context.SaveChangesAsync();
                    await _projectHub.Clients.All.SendAsync("LoadProyects");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectExists(Project.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(Project);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Project == null)
            {
                return NotFound();
            }

            var Project = await _context.Project
                .FirstOrDefaultAsync(m => m.Id == id);
            if (Project == null)
            {
                return NotFound();
            }

            return View(Project);
        }

      
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Project == null)
            {
                return Problem("Entity set 'ApplicationDBContext.Project'  is null.");
            }
            var Project = await _context.Project.FindAsync(id);
            if (Project != null)
            {
                _context.Project.Remove(Project);
            }
            
            await _context.SaveChangesAsync();
            await _projectHub.Clients.All.SendAsync("LoadProyects");
            return RedirectToAction(nameof(Index));
        }

        private bool ProjectExists(int id)
        {
          return (_context.Project?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

PracticaNetSignalR/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PracticaNetSignalR</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/highcharts.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PracticaNetSignalR.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Practica SignalR</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Projects" asp-action="Index">Proyectos</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Chats" asp-action="Index">Chat</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Chats" asp-action="List">Chat (Salas)</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Charts" asp-action="Index">Gráfica</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PracticaNetSignalR - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>